name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 1 * * *'

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Generate the pages that the book will use
    - name: Generate book pages with latest data
      run: |
        papermill --cwd monthly_update monthly_update/run_template.ipynb -
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    # Build the book
    - name: Build the book
      run: |
        jb toc from-project monthly_update/generated/book -e .ipynb -e .md -e .rst --guess-titles > monthly_update/generated/book/_toc.yml
        jb build monthly_update/generated/book

    # Build the people book and move to the book sub-folder
    - name: Build the people book
      run: |
        jb toc from-project monthly_update/generated/people -e .ipynb -e .md -e .rst  --guess-titles > monthly_update/generated/people/_toc.yml
        jb build monthly_update/generated/people
        mv monthly_update/generated/people/_build/html monthly_update/generated/book/_build/html/people

    # Password protect the people pages since this is more sensitive information
    - uses: actions/setup-node@v3
    - run: npm install -g staticrypt
    - run: find monthly_update/generated/book/_build/html/people -type f -name "*.html" -exec staticrypt {} ${{ secrets.MY_PASSWORD }} -o {} \;

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./monthly_update/generated/book/_build/html
